### ISSUE TITLE
Suggestion: remove internal SQLite and GRDB database objects from snapshot

### ISSUE THREAD

**Issue by groue** [SebastianOsinski/GRDBSnapshotTesting#2]
Hello @SebastianOsinski,

Thanks for GRDBSnapshotTesting, it works like a charm 👍 I wanted to suggest a change (two, actually).

Database snapshots currently contain internal SQLite and GRDB objects:

```
======== TABLES ========
CREATE TABLE grdb_migrations (
  identifier TEXT NOT NULL PRIMARY KEY
)

CREATE TABLE sqlite_sequence(
  name
  seq
)

======== DATA ========

## grdb_migrations
...

## sqlite_sequence
...
```

I'm wondering if those objects are useful for the tests.

As internal objects, they can change, without notice, from one version of SQLite or GRDB to another.

I'm also worrying that those objects make it difficult to generate snapshots without relying of the initial snapshot generation (*).

If you agree that we could do without them, then why not exclude them from the snapshot? It is easy to do so: all SQLite [Internal Schema Objects](https://www.sqlite.org/fileformat2.html#internal_schema_objects) have the `sqlite_` prefix. All GRDB internal objects have the `grdb_` prefix (not publicly documented, but I know it firsthand ;-)).

(*) On that second question, I'm also wondering if *sorting objects by name* wouldn't be a net improvement. Sorting objects by name would have another benefit: by easing the comparison between two subsequent schemas with a simple diff, it helps deciding if a snapshot is correct or not.

**Comment by SebastianOsinski** [comment]
Hi!
I also considered hiding those tables from snapshots, as they clutter them a bit. Yet, maybe it would be best to hide them by default but make an option to generate snapshots with them?
Right now we have `static var dbDump` strategy. We could replace it with 
`static func dbDump(includeSQLiteTables: Bool = false, includeGRDBTables: Bool = false)` strategy. This would change making snapshots from `assertSnapshot(matching: db, as: .dbDump)` to `assertSnapshot(matching: db, as: .dbDump())`.

Regarding sorting objects, I also think this is really good idea. Moreover, I think we should add explicit ordering when dumping data from tables. Right now tables are dumped with `SELECT * FROM table_name` and AFAIK this relies on implicit undocumented order and might change between SQLite versions. It should probably be replaced with `SELECT * FROM table_name ORDER BY rowID`. Am I right with this one?

**Comment by groue** [comment]
Thanks for your answer.

> Yet, maybe it would be best to hide them by default but make an option to generate snapshots with them?

Sure, but what is the use case of having them in the snapshot?

> Moreover, I think we should add explicit ordering when dumping data from tables.

This is very true. Quoting https://www.sqlite.org/lang_select.html

> If a SELECT statement that returns more than one row does not have an ORDER BY clause, the order in which the rows are returned is undefined.

Without any ORDER BY clause, SQLite is free to order the rows as it wants, and I presume that the actual order is based on the physical organization of the database file. Slight migrations changes may preserve the content of the database, but maybe not the physical organization, with a risk of breaking tests.

> It should probably be replaced with `SELECT * FROM table_name ORDER BY rowID`. Am I right with this one?

Totally, but... not all tables have a rowid: https://www.sqlite.org/withoutrowid.html:

Sorting by primary key, on the other hand, is guaranteed to work, because all SQLite tables have a primary key (an explicit one, or the implicit rowid, see [PrimaryKeyInfo](http://groue.github.io/GRDB.swift/docs/4.7/Structs/PrimaryKeyInfo.html)).

```swift
let rows = try database.read { db -> [Row] in
    let pk = try db.primaryKey(table)
    let order = pk.columns.joined(separator: ", ")
    return try Row.fetchAll(db, sql: "SELECT * FROM \(table) ORDER BY \(order)")
}
```

In case table and column names would have funky names, I recommend quoting them:

```swift
let rows = try database.read { db -> [Row] in
    let pk = try db.primaryKey(table)
    let order = pk.columns
        .map { $0.quotedDatabaseIdentifier }
        .joined(separator: ", ")
    return try Row.fetchAll(db, sql: """
        SELECT * FROM \(table.quotedDatabaseIdentifier)
        ORDER BY \(order)
        """)
}
```

**Comment by SebastianOsinski** [comment]
> Sure, but what is the use case of having them in the snapshot?

Let's assume we have some `DatabaseConfigurator` which purpose is to set up db by registering migrations in `DatabseMigrator` and then performing them. Wouldn't it be beneficial to have `grdb_migrations` in snapshot to ensure that migrations have been registered (and therefore performed) in correct order? I know that the sole fact of having correct snapshot after all migrations should imply that they have been run in correct order, but this can add one more check for that. 

Of course you know the best how GRDB's internal tables work, so if that's not the case, I'm eager to hide them. 

> Totally, but... not all tables have a rowid

I completely forgot about WITHOUTROWID tables. Thank you for that and the snippets.

**Comment by groue** [comment]
I can see the value of having grdb_migrations in the snapshot, as a free way to tests which migrations have been applied.

But since this table is not documented, you would introduce a dependency on a private GRDB feature inside GRDBSnapshotTesting. When GRDB decides to change the format of the migration table (it is free to do this at any time), tests will break.

Maybe we should instead recommend users to explicitly test for applied migrations with the available public API:

```swift
let appliedMigrations = try migrator.appliedMigrations(in: dbQueue)
XCTAssertEqual(appliedMigrations, ["FooTable", "BarTable", "FixFoo"])
```

**Comment by SebastianOsinski** [comment]
> But since this table is not documented

That's enough for me to agree with you 😅.

So the plan is as follows:
- hide `sqlite_` and `grdb_` tables from snapshots
- order objects (in each group - tables, indexes etc) in snapshot by their name
- order data from tables by primary keys
- after all above are merged, release 1.0 version as these are breaking changes

I plan to work on that during the weekend :)

**Comment by groue** [comment]
That's great, Sebastian :-) I'm very happy to use GRDBSnapshotTesting. It also helps me sharing the schema with my Android coworkers.

**Comment by SebastianOsinski** [comment]
Done in #3
