### ISSUE TITLE
New: groue/GRDBSnapshotTesting

### ISSUE THREAD

**Issue by groue** [SebastianOsinski/GRDBSnapshotTesting#6]
hello @SebastianOsinski,

I just wanted to tell that https://github.com/groue/GRDBSnapshotTesting is now an "official" member of the GRDB family, expected to evolve and be maintained in the long run along with GRDB.

I also wanted to thank you for your excellent idea of providing convenience methods for copying databases from test fixtures. They are now provided by GRDB itself: [`DatabaseQueue.inMemoryCopy(fromPath:configuration:)`](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/databasequeue/inmemorycopy(frompath:configuration:)).

That's it :-)

**Comment by SebastianOsinski** [comment]
Happy to hear that! I'm going to archive this repo then and add a link to your repo :)
